# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.qrph.madx
canonical: https://profiles.ihe.net/QRPH/mADX
version: 0.0.1-current
name: IHE_QRPH_mADX
title: "Mobile Aggregate Data Exchange"
description: The Mobile Aggregate Data Exchange (mADX) Profile supports interoperable public health reporting of aggregate health data. These most typically take the form of routine reports (weekly, monthly, quarterly etc.) from a health facility to some administrative jurisdiction such as a health district, though there are numerous other use cases such as international reporting and community health worker reporting.
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: trial-use
#releaseLabel: release
#date: 2022-01-02
status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE QRPH Technical Committee
  - url: https://www.ihe.net/ihe_domains/quality_research_and_public_health/
  - email: qrph@ihe.net
contact:
  - name: IHE QRPH Technical Committee
    telecom:
      - system: email
        value: qrph@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+

dependencies:
 hl7.fhir.uv.crmi:
    id: crmi
    version: 1.0.0
    reason: This IG uses content management profiles and capabilities provided by the Canonical Resource Management Infrastructure (CRMI) IG

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: Mobile Aggregate Data Exchange (mADX) Home
    generation: markdown
  volume-1.md:
    title: 1:6 Mobile Aggregate Data Exchange (mADX)
    generation: markdown
  QRPH-58.md:
    title: 2:3.58 Send Aggregate Report [QRPH-58]
    generation: markdown
  QRPH-59.md:
    title: 2:3.59 Retrieve Aggregate Report Definition [QRPH-59]
    generation: markdown
  volume-3.md:
    title: Content Modules
    generation: markdown
  testplan.md:
    title: Test Plan
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  download.md:
    title: Download and Analysis
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  mADX Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors, Transactions and Content Modules: volume-1.html#actors-transactions-content-modules
    Actor Options: volume-1.html#actor-options
    Required Actor Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
  Volume 2:
    "Send Aggregate Report [QRPH-58]": QRPH-58.html
    "Retrieve Aggregate Report Definition [QRPH-59]": QRPH-59.html
  Volume 3:
    "Content Modules": volume-3.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html
